#projectlibertina.py - Recreates the text contents of http://projectlibertina.com (a Doki Doki Literature Club easter egg)
#into a Python output using print() statements. The original text was just black, but I may add some colour.

#Licensed under Creative Commons Public Domain (CC0). Do you what you wish with this code.

#The <title></title> tags of the page were 11 percentage symbols: "%%%%%%%%%%%"
#I'm unsure if that's relevant.

print("================================================================================")
print("MONTHLY EXAMINATION REPORT                                       January 5, 2004")
print("================================================================================")
print()                                                                               
print()                                                                               
print("====SUBJECT INFO")                                                             
print()                                                                               
print("Name                                                            XXXXXX, Libitina")
print("DOB                                                                   01/05/2001")
print("Sex                                                                            F")
print("Age                                                                            3")
print("Height                                                                        35")
print("Weight                                                                        31")
print("Wing                                                                           A")
print("Room                                                                         114")
print("--------------------------------------------------------------------------------")
print("Significance Level (001-100)                                                 100")
print("--------------------------------------------------------------------------------")
print()                                                                                
print()                                                                            
print("====SUBJECT NOTES")                                                    
print()                                                                                
print("Last Updated                                                          12/05/2003")
print("--------------------------------------------------------------------------------")
print("As of December 5th, 2003, all personnel are forbidden from editing this field.") 
print("All previous subject notes have been erased permanently.")                 
print("Addendum: Introducing bias during testing as a result of personal attachment to")
print("the subject will henceforth be punished by death.")                
print("--------------------------------------------------------------------------------")
print()
print()
print("====PHYSICAL RESULTS")
print()
print("BMI                                                                         17.8")
print("HR                                                                            90")
print("SP                                                                           101")
print("DP                                                                            59")
print("TMP                                                                         98.6")
print()                                                                             
print("Eyes                                                                      Normal")
print("Ears                                                                      Normal")
print("Teeth                                                                     Normal")
print("Genitals                                                                  Normal")
print("Pain tolerance (01-10)                                                        03")
print()                                                                  
print()                                                                      
print("====PHYSICAL RESULTS (THIRD EYE)")                                            
print()                                                                               
print("HR                                                                           160")
print("Reaction time (ms)                                                             1")
print("Strength                                                                     N/A")
print("Local distortion                                                             434")
print("Distortion decay                                                              29")
print("Positivity (01-10)                                                            01")
print("Sensitivity (01-10)                                                           09")
print("Control (01-10)                                                               01")
print()
print()
print("====PHYSICAL NOTES")                                                          
print()                                                                       
print("Last Updated                                                          01/05/2004")
print("--------------------------------------------------------------------------------")
print("The following occasional behaviors have been noted and should be ignored in")
print("future examinations:")                                                            
print("Twitching; vocal tics; biting; epiphora; vomiting; screaming; harm to examiner;")
print("harm to self; misplaced laughter")                         
print("Any self-harm attempts must be interrupted immediately.")                        
print("--------------------------------------------------------------------------------")
print()                                                                            
print()                                                                              
print("====TEST RESULTS")                                                      
print()                                                                                
print("Physical Response Test                                          100       PASSED")
print("Emotional Response Test                                         100       PASSED")
print("Physical Control Test                                            32       FAILED")
print("Emotional Control Test                                           22       FAILED")
print("Third Eye Activation Test                                       100       PASSED")
print("Third Eye Suppression Test                                       08       FAILED")
print()                                                                              
print("Sexual Response Test                                            N/A          N/A")
print()                                                                              
print("Minor Threat Response Test                                      100       PASSED")
print("Minor Threat Elimination Test                                   100       PASSED")
print("Life Threat Response Test                                       100       PASSED")
print("Life Threat Elimination Test                                    100       PASSED")
print()                                                                               
print()                                                                               
print("====TEST NOTES")                                                     
print()                                                                     
print("Last Updated                                                          01/05/2004")
print("--------------------------------------------------------------------------------")
print("Sexual Response Test is bypassed during prepubescence.")                          
print("Requested bypassing the following tests:")                                       
print("Third Eye Activation Test; Third Eye Suppression Test; Life Threat Response")     
print("Test; Life Threat Elimination Test.")                                             
print("All requests denied.")                                                        
print()                                                                              
print("Libitina has not yet recovered from the termination of XXXXXX and is not")   
print("expected to do so in the near future. Continuing to administer these tests will")
print("only accelerate the deterioration of Libitina's health.")                         
print("You are choosing to avoid the measures necessary to prevent a repeat scenario,")
print("Doctor. Will you not have as much faith in your personnel as you do in your God?")
print("--------------------------------------------------------------------------------")
print()                                                                               
print()                                                                                
print("================================================================================")
print("END OF REPORT")                                                                 
print("================================================================================")